### ISSUE TITLE
Getting connection aborted message when processing pdf files

### ISSUE THREAD

**Issue by minump** [clowder-framework/CONSORT-frontend#68]
When uploading a pdf file, the pdf2text-extractor kicks in, after "submission for extraction", multiple "Connection aborted" messages are being logged.

The file is again submitted for extraction and the cycle repeats. This is noticed in the local instance when extracting large pdf files. Not able to check this out in consort instance because of radiant volume detaching issue.

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/pyclowder/connectors.py", line 434, in _process_message

    self.process_message(self, source_host, secret_key, resource, body)

  File "//pdf2text.py", line 56, in process_message

    output_xml_file, output_json_file, output_txt_file = process_pdf_file(input_file, input_filename, temp_dir, output_dir)

  File "/doc2txt/grobid2json/process_pdf.py", line 74, in process_pdf_file

    client.process_pdf(input_file, input_filename, temp_dir, "processFulltextDocument")

  File "/doc2txt/grobid2json/grobid/grobid_client.py", line 154, in process_pdf

    tei_text = self.process_pdf_stream(input_filename, pdf_strm, output, service)

  File "/doc2txt/grobid2json/grobid/grobid_client.py", line 125, in process_pdf_stream

    res, status = self.post(

  File "/doc2txt/grobid2json/grobid/client.py", line 205, in post

    return self.call_api(

  File "/doc2txt/grobid2json/grobid/client.py", line 126, in call_api

    r = requests.request(

  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 60, in request

    return session.request(method=method, url=url, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 533, in request

    resp = self.send(prep, **send_kwargs)

  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 646, in send

    r = adapter.send(request, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 498, in send

    raise ConnectionError(err, request=request)

requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

2023-11-07 15:56:34,679 [Thread-15 (_process_message)] INFO    : pyclowder.connectors - [654a5da2e4b051a0ae4d5257] : StatusMessage.error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

<img width="1080" alt="Screenshot 2023-11-07 at 9 59 28 AM" src="https://github.com/clowder-framework/CONSORT-frontend/assets/22112888/9d16b9b6-de4c-44f5-9f9a-4eaf8471b6e9">

**Comment by minump** [comment]
Was not able to reproduce this bug again. Closing this issue.
